// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Aiming: typeof import('./../components/icons/Aiming.vue')['default']
    Alarm: typeof import('./../components/icons/Alarm.vue')['default']
    Alarm_4ki1513l: typeof import('./../components/icons/Alarm_4ki1513l.vue')['default']
    Bill: typeof import('./../components/icons/Bill.vue')['default']
    BookmarkOne: typeof import('./../components/icons/BookmarkOne.vue')['default']
    BroadcastRadio: typeof import('./../components/icons/BroadcastRadio.vue')['default']
    BroadcastRadio_4kh67a3g: typeof import('./../components/icons/BroadcastRadio_4kh67a3g.vue')['default']
    Bug: typeof import('./../components/icons/Bug.vue')['default']
    Delete: typeof import('./../components/icons/Delete.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
  }
}

export { }
